---
title: "Readme RadChart Function"
author: "Juan Carlos Rubio Polania"
date: "05/01/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, error=TRUE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, error= TRUE, warning=FALSE)
``` 

# RadChart

RadChart function provides three different ways to plot radar charts. The first option allows plot vector values and has a mandatory argument "Vec" that provides the main title. The second option provides a way to plot multiple radar charts from data tables, whereby the graphic function par could be useful together with the argument mfrow (to set the rows and columns of the composed figure). Those above options require the use of col1 and col2 arguments; however, in the third option, col2 must be absent, because the colors are provided automatically. This last option has "MV" as a mandatory argument that determines the main title, and provides a single radar chart with at least three variables, samples, or stations. 

### Function Arguments

* df =  It is the data frame with stations in columns and the variables in rows. Also, this argument could be a vector.
* Ftext = Selected font for the labels, numbers, and titles. 
* col1 = Selected color for radar chart grid.
* col2 = Selected color for filling the polygons got by dots union, this argument is unused with the multivariate version of RadChart function.
* Vec = This is an argument exclusive and mandatory to do radar charts from vectors, it provides the main title. 
* MV = This argument is an exclusive and mandatory of the multivariate version of this function, and provides the main title.

Note: The RadChart function shows an error "the argument "df" is absent, no default value in r" when it runs empty; however, the function works correctly.

The following lines are examples of the different radar chart got from the datasets available as examples in the global environment of r.

### Loading data to plotting

#### Dataset OrchardSprays (it has data of Potency of Orchard Sprays)

data(OrchardSprays)

Here was created the vector using few data of decrease column of OrchardSprays data set.

par(mfrow=c(1,1))
decrease=OrchardSprays$decrease[1:6]
decrease

RadChart(decrease,"Perpetua Titling MT","black","dodgerblue",Vec="Decrease")
#dev.copy(device=jpeg,filename="OrchardSpraysUni.jpeg",width=800,height=800);
#dev.off()

par(mfrow=c(2,2))
RadChart(OrchardSprays[c(1:3,9:15),1:3],"Niagara Engraved","black","brown4")
#dev.copy(device=jpeg,filename="OrchardSpraysBi.jpeg",width=800,height=800);
#dev.off()

par(mfrow=c(1,1))
RadChart(OrchardSprays[c(1:2,9:11),1:3],"Malgun Gothic","black",MV="OrchardSprays Dataset")
#dev.copy(device=jpeg,filename="OrchardSpraysMulti.jpeg",width=800,height=800);
#dev.off()

#### Dataset Orange (it has data about Growth of Orange Trees)

In this step to show the vector option the first column of Orange dataset was converted from factor to numeric.

data(Orange)
Orange$NTree=as.numeric(as.character(Orange$Tree))

par(mfrow=c(1,1))
nt=Orange$NTree[c(1:2,8:10,18:20,22:25,31:34)]
par(mfrow=c(1,1))
RadChart(nt,"Matura MT Script Capitals","black","firebrick",Vec="NTree")
#dev.copy(device=jpeg,filename="OrangeUni.jpeg",width=800,height=800);
#dev.off()

par(mfrow=c(1,1))
Age=Orange$circumference[1:7]
par(mfrow=c(1,1))
RadChart(Age,"Rockwell Extra Bold","black","red",Vec="Circumference")
#dev.copy(device=jpeg,filename="OrangeUni.jpeg",width=800,height=800);
#dev.off()

par(mfrow=c(2,2))
RadChart(Orange[1:8,2:4],"Eras Demi ITC","black","forestgreen")
#dev.copy(device=jpeg,filename="OrangeBi.jpeg",width=800,height=800);
#dev.off()

par(mfrow=c(1,1))
RadChart(Orange[c(1:2,5:7,9:11),2:4],"Jokerman","black",MV="Orange Dataset")
#dev.copy(device=jpeg,filename="OrangeMulti.jpeg",width=800,height=800);
#dev.off()

#### Dataset Iris. It is the Edgar Anderson's Iris Data (it has information about the measures about four feature of the three species of genus Iris)

The vector of this dataset was got through sample function using 10 values

data(iris)
iris$ASepal=iris$Sepal.Length*iris$Sepal.Width
iris$APetal=iris$Petal.Length*iris$Petal.Width

width=sample(iris$Sepal.Width,10)
par(mfrow=c(1,1))
RadChart(width,"Garamond","deepskyblue3","darkgreen",Vec="width")
#dev.copy(device=jpeg,filename="IrisUni.jpeg",width=800,height=800);
#dev.off()

par(mfrow=c(2,2))
RadChart(iris[1:10,1:4],"Book Antiqua","blue4","darkgoldenrod")
#dev.copy(device=jpeg,filename="IrisBi.jpeg",width=800,height=800);
#dev.off()

par(mfrow=c(1,1))
colnames(iris)=c("LSepal","WSepal","LPetal","WPetal","Species","ASepal","APetal")
RadChart(iris[7:10,c(1:4,6:7)],"Pristina","blue4",MV="Iris Dataset")
#dev.copy(device=jpeg,filename="IrisMulti.jpeg",width=800,height=800);
#dev.off()

#### Dataset mtcars (it has information about Motor Trend Car Road Tests)

The rownames in this dataset can be too long to use as axis labels; therefore, they were abbreviated using the function abbreviate.

data(mtcars)
rownames(mtcars)=abbreviate(rownames(mtcars))

HorsePower=mtcars$hp[7:24]

par(mfrow=c(1,1))
RadChart(HorsePower,"Javanese Text","black","indianred4",Vec="Horse Power")
#dev.copy(device=jpeg,filename="MtcarsUni.jpeg",width=800,height=800);
#dev.off()

par(mfrow=c(2,2))
RadChart(mtcars[1:8,1:4],"Tahoma","black","brown")
#dev.copy(device=jpeg,filename="MtcarsBi.jpeg",width=800,height=800);
#dev.off()

par(mfrow=c(1,1))
RadChart(mtcars[c(1,8,15),1:6],"Old English Text MT","red",MV="Mtcars Dataset")
#dev.copy(device=jpeg,filename="MtcarsMulti.jpeg",width=800,height=800);
#dev.off()
